services:
  api:
    container_name: po-api
    build: .
    env_file: ".env"
    ports:
      - '2736'
    restart: unless-stopped
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  rabbitmq:
    container_name: po-rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '2735:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  https-portal:
    container_name: po-https
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
    restart: unless-stopped
    environment:
      DOMAINS: 'api.rileyherman.ca-> http://po-api:2736'
#      STAGE: 'production'
