services:
  api:
    build:
      context: .
      dockerfile: ./docker/helper/Dockerfile
    env_file: ".env"
    ports:
      - '2736:2736'
    restart: unless-stopped

  arch2:
    build:
      context: .
      dockerfile: ./docker/arch2/Dockerfile
    env_file: ".env"
    restart: unless-stopped

  main:
    build:
      context: .
      dockerfile: ./docker/main/Dockerfile
    env_file: ".env"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file: ".env"
    ports:
      - '5672:5672'
      - '15672:15672'

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
    restart: always
    environment:
      DOMAINS: 'api.rileyherman.ca-> http://api:2736'
      STAGE: 'production'

