services:
  api:
    build: .
    env_file: ".env"
    ports:
      - '2736'
    restart: always

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
      - rabbitmq
    restart: always
    environment:
      DOMAINS: 'api.rileyherman.ca-> http://api:2736, api.rileyherman.ca:5672 -> http://rabbitmq:5672'
  #      STAGE: 'production'


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '2735:15672'
    env_file: ".rabbitmq.env"
