services:
  api:
    build: .
    env_file: ".env"
    ports:
      - '2736'
    restart: always

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
    restart: always
    environment:
      DOMAINS: 'api.rileyherman.ca-> http://api:2736'
  #      STAGE: 'production'

