services:
    mongo:
        ports:
            - '27017:27017'
        container_name: local-mongo
        restart: unless-stopped
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        image: mongo